//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:fatca:v2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:oecd:ties:fatca:v2", IsNullable=false)]
public partial class FATCA_OECD {
    
    private MessageSpec_Type messageSpecField;
    
    private Fatca_Type[] fATCAField;
    
    private string versionField;
    
    /// <remarks/>
    public MessageSpec_Type MessageSpec {
        get {
            return this.messageSpecField;
        }
        set {
            this.messageSpecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FATCA")]
    public Fatca_Type[] FATCA {
        get {
            return this.fATCAField;
        }
        set {
            this.fATCAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class MessageSpec_Type {
    
    private string sendingCompanyINField;
    
    private CountryCode_Type transmittingCountryField;
    
    private CountryCode_Type receivingCountryField;
    
    private MessageType_EnumType messageTypeField;
    
    private string warningField;
    
    private string contactField;
    
    private string messageRefIdField;
    
    private string[] corrMessageRefIdField;
    
    private System.DateTime reportingPeriodField;
    
    private System.DateTime timestampField;
    
    /// <remarks/>
    public string SendingCompanyIN {
        get {
            return this.sendingCompanyINField;
        }
        set {
            this.sendingCompanyINField = value;
        }
    }
    
    /// <remarks/>
    public CountryCode_Type TransmittingCountry {
        get {
            return this.transmittingCountryField;
        }
        set {
            this.transmittingCountryField = value;
        }
    }
    
    /// <remarks/>
    public CountryCode_Type ReceivingCountry {
        get {
            return this.receivingCountryField;
        }
        set {
            this.receivingCountryField = value;
        }
    }
    
    /// <remarks/>
    public MessageType_EnumType MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Warning {
        get {
            return this.warningField;
        }
        set {
            this.warningField = value;
        }
    }
    
    /// <remarks/>
    public string Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    public string MessageRefId {
        get {
            return this.messageRefIdField;
        }
        set {
            this.messageRefIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CorrMessageRefId")]
    public string[] CorrMessageRefId {
        get {
            return this.corrMessageRefIdField;
        }
        set {
            this.corrMessageRefIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ReportingPeriod {
        get {
            return this.reportingPeriodField;
        }
        set {
            this.reportingPeriodField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:isofatcatypes:v1")]
public enum CountryCode_Type {
    
    /// <remarks/>
    AF,
    
    /// <remarks/>
    AX,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    DZ,
    
    /// <remarks/>
    AS,
    
    /// <remarks/>
    AD,
    
    /// <remarks/>
    AO,
    
    /// <remarks/>
    AI,
    
    /// <remarks/>
    AQ,
    
    /// <remarks/>
    AG,
    
    /// <remarks/>
    AR,
    
    /// <remarks/>
    AM,
    
    /// <remarks/>
    AW,
    
    /// <remarks/>
    AU,
    
    /// <remarks/>
    AT,
    
    /// <remarks/>
    AZ,
    
    /// <remarks/>
    BS,
    
    /// <remarks/>
    BH,
    
    /// <remarks/>
    BD,
    
    /// <remarks/>
    BB,
    
    /// <remarks/>
    BY,
    
    /// <remarks/>
    BE,
    
    /// <remarks/>
    BZ,
    
    /// <remarks/>
    BJ,
    
    /// <remarks/>
    BM,
    
    /// <remarks/>
    BT,
    
    /// <remarks/>
    BO,
    
    /// <remarks/>
    BQ,
    
    /// <remarks/>
    BA,
    
    /// <remarks/>
    BW,
    
    /// <remarks/>
    BV,
    
    /// <remarks/>
    BR,
    
    /// <remarks/>
    IO,
    
    /// <remarks/>
    BN,
    
    /// <remarks/>
    BG,
    
    /// <remarks/>
    BF,
    
    /// <remarks/>
    BI,
    
    /// <remarks/>
    KH,
    
    /// <remarks/>
    CM,
    
    /// <remarks/>
    CA,
    
    /// <remarks/>
    CV,
    
    /// <remarks/>
    KY,
    
    /// <remarks/>
    CF,
    
    /// <remarks/>
    TD,
    
    /// <remarks/>
    CL,
    
    /// <remarks/>
    CN,
    
    /// <remarks/>
    CX,
    
    /// <remarks/>
    CC,
    
    /// <remarks/>
    CO,
    
    /// <remarks/>
    KM,
    
    /// <remarks/>
    CG,
    
    /// <remarks/>
    CD,
    
    /// <remarks/>
    CK,
    
    /// <remarks/>
    CR,
    
    /// <remarks/>
    CI,
    
    /// <remarks/>
    HR,
    
    /// <remarks/>
    CU,
    
    /// <remarks/>
    CW,
    
    /// <remarks/>
    CY,
    
    /// <remarks/>
    CZ,
    
    /// <remarks/>
    DK,
    
    /// <remarks/>
    DJ,
    
    /// <remarks/>
    DM,
    
    /// <remarks/>
    DO,
    
    /// <remarks/>
    EC,
    
    /// <remarks/>
    EG,
    
    /// <remarks/>
    SV,
    
    /// <remarks/>
    GQ,
    
    /// <remarks/>
    ER,
    
    /// <remarks/>
    EE,
    
    /// <remarks/>
    ET,
    
    /// <remarks/>
    FK,
    
    /// <remarks/>
    FO,
    
    /// <remarks/>
    FJ,
    
    /// <remarks/>
    FI,
    
    /// <remarks/>
    FR,
    
    /// <remarks/>
    GF,
    
    /// <remarks/>
    PF,
    
    /// <remarks/>
    TF,
    
    /// <remarks/>
    GA,
    
    /// <remarks/>
    GM,
    
    /// <remarks/>
    GE,
    
    /// <remarks/>
    DE,
    
    /// <remarks/>
    GH,
    
    /// <remarks/>
    GI,
    
    /// <remarks/>
    GR,
    
    /// <remarks/>
    GL,
    
    /// <remarks/>
    GD,
    
    /// <remarks/>
    GP,
    
    /// <remarks/>
    GU,
    
    /// <remarks/>
    GT,
    
    /// <remarks/>
    GG,
    
    /// <remarks/>
    GN,
    
    /// <remarks/>
    GW,
    
    /// <remarks/>
    GY,
    
    /// <remarks/>
    HT,
    
    /// <remarks/>
    HM,
    
    /// <remarks/>
    VA,
    
    /// <remarks/>
    HN,
    
    /// <remarks/>
    HK,
    
    /// <remarks/>
    HU,
    
    /// <remarks/>
    IS,
    
    /// <remarks/>
    IN,
    
    /// <remarks/>
    ID,
    
    /// <remarks/>
    IR,
    
    /// <remarks/>
    IQ,
    
    /// <remarks/>
    IE,
    
    /// <remarks/>
    IM,
    
    /// <remarks/>
    IL,
    
    /// <remarks/>
    IT,
    
    /// <remarks/>
    JM,
    
    /// <remarks/>
    JP,
    
    /// <remarks/>
    JE,
    
    /// <remarks/>
    JO,
    
    /// <remarks/>
    KZ,
    
    /// <remarks/>
    KE,
    
    /// <remarks/>
    KI,
    
    /// <remarks/>
    XK,
    
    /// <remarks/>
    KP,
    
    /// <remarks/>
    KR,
    
    /// <remarks/>
    KW,
    
    /// <remarks/>
    KG,
    
    /// <remarks/>
    LA,
    
    /// <remarks/>
    LV,
    
    /// <remarks/>
    LB,
    
    /// <remarks/>
    LS,
    
    /// <remarks/>
    LR,
    
    /// <remarks/>
    LY,
    
    /// <remarks/>
    LI,
    
    /// <remarks/>
    LT,
    
    /// <remarks/>
    LU,
    
    /// <remarks/>
    MO,
    
    /// <remarks/>
    MK,
    
    /// <remarks/>
    MG,
    
    /// <remarks/>
    MW,
    
    /// <remarks/>
    MY,
    
    /// <remarks/>
    MV,
    
    /// <remarks/>
    ML,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    MH,
    
    /// <remarks/>
    MQ,
    
    /// <remarks/>
    MR,
    
    /// <remarks/>
    MU,
    
    /// <remarks/>
    YT,
    
    /// <remarks/>
    MX,
    
    /// <remarks/>
    FM,
    
    /// <remarks/>
    MD,
    
    /// <remarks/>
    MC,
    
    /// <remarks/>
    MN,
    
    /// <remarks/>
    ME,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MZ,
    
    /// <remarks/>
    MM,
    
    /// <remarks/>
    NA,
    
    /// <remarks/>
    NR,
    
    /// <remarks/>
    NP,
    
    /// <remarks/>
    NL,
    
    /// <remarks/>
    NC,
    
    /// <remarks/>
    NZ,
    
    /// <remarks/>
    NI,
    
    /// <remarks/>
    NE,
    
    /// <remarks/>
    NG,
    
    /// <remarks/>
    NU,
    
    /// <remarks/>
    NF,
    
    /// <remarks/>
    MP,
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    OM,
    
    /// <remarks/>
    PK,
    
    /// <remarks/>
    PW,
    
    /// <remarks/>
    PS,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PG,
    
    /// <remarks/>
    PY,
    
    /// <remarks/>
    PE,
    
    /// <remarks/>
    PH,
    
    /// <remarks/>
    PN,
    
    /// <remarks/>
    PL,
    
    /// <remarks/>
    PT,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    QA,
    
    /// <remarks/>
    RE,
    
    /// <remarks/>
    RO,
    
    /// <remarks/>
    RU,
    
    /// <remarks/>
    RW,
    
    /// <remarks/>
    BL,
    
    /// <remarks/>
    SH,
    
    /// <remarks/>
    KN,
    
    /// <remarks/>
    LC,
    
    /// <remarks/>
    MF,
    
    /// <remarks/>
    PM,
    
    /// <remarks/>
    VC,
    
    /// <remarks/>
    WS,
    
    /// <remarks/>
    SM,
    
    /// <remarks/>
    ST,
    
    /// <remarks/>
    SA,
    
    /// <remarks/>
    SN,
    
    /// <remarks/>
    RS,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SL,
    
    /// <remarks/>
    SG,
    
    /// <remarks/>
    SX,
    
    /// <remarks/>
    SK,
    
    /// <remarks/>
    SI,
    
    /// <remarks/>
    SB,
    
    /// <remarks/>
    SO,
    
    /// <remarks/>
    ZA,
    
    /// <remarks/>
    GS,
    
    /// <remarks/>
    SS,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    LK,
    
    /// <remarks/>
    SD,
    
    /// <remarks/>
    SR,
    
    /// <remarks/>
    SJ,
    
    /// <remarks/>
    SZ,
    
    /// <remarks/>
    SE,
    
    /// <remarks/>
    CH,
    
    /// <remarks/>
    SY,
    
    /// <remarks/>
    TW,
    
    /// <remarks/>
    TJ,
    
    /// <remarks/>
    TZ,
    
    /// <remarks/>
    TH,
    
    /// <remarks/>
    TL,
    
    /// <remarks/>
    TG,
    
    /// <remarks/>
    TK,
    
    /// <remarks/>
    TO,
    
    /// <remarks/>
    TT,
    
    /// <remarks/>
    TN,
    
    /// <remarks/>
    TR,
    
    /// <remarks/>
    TM,
    
    /// <remarks/>
    TC,
    
    /// <remarks/>
    TV,
    
    /// <remarks/>
    UG,
    
    /// <remarks/>
    UA,
    
    /// <remarks/>
    AE,
    
    /// <remarks/>
    GB,
    
    /// <remarks/>
    US,
    
    /// <remarks/>
    UM,
    
    /// <remarks/>
    UY,
    
    /// <remarks/>
    UZ,
    
    /// <remarks/>
    VU,
    
    /// <remarks/>
    VE,
    
    /// <remarks/>
    VN,
    
    /// <remarks/>
    VG,
    
    /// <remarks/>
    VI,
    
    /// <remarks/>
    WF,
    
    /// <remarks/>
    EH,
    
    /// <remarks/>
    YE,
    
    /// <remarks/>
    ZM,
    
    /// <remarks/>
    ZW,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stffatcatypes:v2")]
public enum MessageType_EnumType {
    
    /// <remarks/>
    FATCA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class CorrectablePoolReport_Type {
    
    private DocSpec_Type docSpecField;
    
    private string accountCountField;
    
    private FatcaAcctPoolReportType_EnumType accountPoolReportTypeField;
    
    private MonAmnt_Type poolBalanceField;
    
    /// <remarks/>
    public DocSpec_Type DocSpec {
        get {
            return this.docSpecField;
        }
        set {
            this.docSpecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string AccountCount {
        get {
            return this.accountCountField;
        }
        set {
            this.accountCountField = value;
        }
    }
    
    /// <remarks/>
    public FatcaAcctPoolReportType_EnumType AccountPoolReportType {
        get {
            return this.accountPoolReportTypeField;
        }
        set {
            this.accountPoolReportTypeField = value;
        }
    }
    
    /// <remarks/>
    public MonAmnt_Type PoolBalance {
        get {
            return this.poolBalanceField;
        }
        set {
            this.poolBalanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class DocSpec_Type {
    
    private FatcaDocTypeIndic_EnumType docTypeIndicField;
    
    private string docRefIdField;
    
    private string corrMessageRefIdField;
    
    private string corrDocRefIdField;
    
    /// <remarks/>
    public FatcaDocTypeIndic_EnumType DocTypeIndic {
        get {
            return this.docTypeIndicField;
        }
        set {
            this.docTypeIndicField = value;
        }
    }
    
    /// <remarks/>
    public string DocRefId {
        get {
            return this.docRefIdField;
        }
        set {
            this.docRefIdField = value;
        }
    }
    
    /// <remarks/>
    public string CorrMessageRefId {
        get {
            return this.corrMessageRefIdField;
        }
        set {
            this.corrMessageRefIdField = value;
        }
    }
    
    /// <remarks/>
    public string CorrDocRefId {
        get {
            return this.corrDocRefIdField;
        }
        set {
            this.corrDocRefIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public enum FatcaDocTypeIndic_EnumType {
    
    /// <remarks/>
    FATCA1,
    
    /// <remarks/>
    FATCA2,
    
    /// <remarks/>
    FATCA3,
    
    /// <remarks/>
    FATCA4,
    
    /// <remarks/>
    FATCA11,
    
    /// <remarks/>
    FATCA12,
    
    /// <remarks/>
    FATCA13,
    
    /// <remarks/>
    FATCA14,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public enum FatcaAcctPoolReportType_EnumType {
    
    /// <remarks/>
    FATCA201,
    
    /// <remarks/>
    FATCA202,
    
    /// <remarks/>
    FATCA203,
    
    /// <remarks/>
    FATCA204,
    
    /// <remarks/>
    FATCA205,
    
    /// <remarks/>
    FATCA206,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class MonAmnt_Type {
    
    private currCode_Type currCodeField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public currCode_Type currCode {
        get {
            return this.currCodeField;
        }
        set {
            this.currCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:isofatcatypes:v1")]
public enum currCode_Type {
    
    /// <remarks/>
    AED,
    
    /// <remarks/>
    AFN,
    
    /// <remarks/>
    ALL,
    
    /// <remarks/>
    AMD,
    
    /// <remarks/>
    ANG,
    
    /// <remarks/>
    AOA,
    
    /// <remarks/>
    ARS,
    
    /// <remarks/>
    AUD,
    
    /// <remarks/>
    AWG,
    
    /// <remarks/>
    AZN,
    
    /// <remarks/>
    BAM,
    
    /// <remarks/>
    BBD,
    
    /// <remarks/>
    BDT,
    
    /// <remarks/>
    BGN,
    
    /// <remarks/>
    BHD,
    
    /// <remarks/>
    BIF,
    
    /// <remarks/>
    BMD,
    
    /// <remarks/>
    BND,
    
    /// <remarks/>
    BOB,
    
    /// <remarks/>
    BOV,
    
    /// <remarks/>
    BRL,
    
    /// <remarks/>
    BSD,
    
    /// <remarks/>
    BTN,
    
    /// <remarks/>
    BWP,
    
    /// <remarks/>
    BYR,
    
    /// <remarks/>
    BZD,
    
    /// <remarks/>
    CAD,
    
    /// <remarks/>
    CDF,
    
    /// <remarks/>
    CHE,
    
    /// <remarks/>
    CHF,
    
    /// <remarks/>
    CHW,
    
    /// <remarks/>
    CLF,
    
    /// <remarks/>
    CLP,
    
    /// <remarks/>
    CNY,
    
    /// <remarks/>
    COP,
    
    /// <remarks/>
    COU,
    
    /// <remarks/>
    CRC,
    
    /// <remarks/>
    CUC,
    
    /// <remarks/>
    CUP,
    
    /// <remarks/>
    CVE,
    
    /// <remarks/>
    CZK,
    
    /// <remarks/>
    DJF,
    
    /// <remarks/>
    DKK,
    
    /// <remarks/>
    DOP,
    
    /// <remarks/>
    DZD,
    
    /// <remarks/>
    EGP,
    
    /// <remarks/>
    ERN,
    
    /// <remarks/>
    ETB,
    
    /// <remarks/>
    EUR,
    
    /// <remarks/>
    FJD,
    
    /// <remarks/>
    FKP,
    
    /// <remarks/>
    GBP,
    
    /// <remarks/>
    GEL,
    
    /// <remarks/>
    GHS,
    
    /// <remarks/>
    GIP,
    
    /// <remarks/>
    GMD,
    
    /// <remarks/>
    GNF,
    
    /// <remarks/>
    GTQ,
    
    /// <remarks/>
    GYD,
    
    /// <remarks/>
    HKD,
    
    /// <remarks/>
    HNL,
    
    /// <remarks/>
    HRK,
    
    /// <remarks/>
    HTG,
    
    /// <remarks/>
    HUF,
    
    /// <remarks/>
    IDR,
    
    /// <remarks/>
    ILS,
    
    /// <remarks/>
    INR,
    
    /// <remarks/>
    IQD,
    
    /// <remarks/>
    IRR,
    
    /// <remarks/>
    ISK,
    
    /// <remarks/>
    JMD,
    
    /// <remarks/>
    JOD,
    
    /// <remarks/>
    JPY,
    
    /// <remarks/>
    KES,
    
    /// <remarks/>
    KGS,
    
    /// <remarks/>
    KHR,
    
    /// <remarks/>
    KMF,
    
    /// <remarks/>
    KPW,
    
    /// <remarks/>
    KRW,
    
    /// <remarks/>
    KWD,
    
    /// <remarks/>
    KYD,
    
    /// <remarks/>
    KZT,
    
    /// <remarks/>
    LAK,
    
    /// <remarks/>
    LBP,
    
    /// <remarks/>
    LKR,
    
    /// <remarks/>
    LRD,
    
    /// <remarks/>
    LSL,
    
    /// <remarks/>
    LTL,
    
    /// <remarks/>
    LVL,
    
    /// <remarks/>
    LYD,
    
    /// <remarks/>
    MAD,
    
    /// <remarks/>
    MDL,
    
    /// <remarks/>
    MGA,
    
    /// <remarks/>
    MKD,
    
    /// <remarks/>
    MMK,
    
    /// <remarks/>
    MNT,
    
    /// <remarks/>
    MOP,
    
    /// <remarks/>
    MRO,
    
    /// <remarks/>
    MUR,
    
    /// <remarks/>
    MVR,
    
    /// <remarks/>
    MWK,
    
    /// <remarks/>
    MXN,
    
    /// <remarks/>
    MXV,
    
    /// <remarks/>
    MYR,
    
    /// <remarks/>
    MZN,
    
    /// <remarks/>
    NAD,
    
    /// <remarks/>
    NGN,
    
    /// <remarks/>
    NIO,
    
    /// <remarks/>
    NOK,
    
    /// <remarks/>
    NPR,
    
    /// <remarks/>
    NZD,
    
    /// <remarks/>
    OMR,
    
    /// <remarks/>
    PAB,
    
    /// <remarks/>
    PEN,
    
    /// <remarks/>
    PGK,
    
    /// <remarks/>
    PHP,
    
    /// <remarks/>
    PKR,
    
    /// <remarks/>
    PLN,
    
    /// <remarks/>
    PYG,
    
    /// <remarks/>
    QAR,
    
    /// <remarks/>
    RON,
    
    /// <remarks/>
    RSD,
    
    /// <remarks/>
    RUB,
    
    /// <remarks/>
    RWF,
    
    /// <remarks/>
    SAR,
    
    /// <remarks/>
    SBD,
    
    /// <remarks/>
    SCR,
    
    /// <remarks/>
    SDG,
    
    /// <remarks/>
    SEK,
    
    /// <remarks/>
    SGD,
    
    /// <remarks/>
    SHP,
    
    /// <remarks/>
    SLL,
    
    /// <remarks/>
    SOS,
    
    /// <remarks/>
    SRD,
    
    /// <remarks/>
    SSP,
    
    /// <remarks/>
    STD,
    
    /// <remarks/>
    SVC,
    
    /// <remarks/>
    SYP,
    
    /// <remarks/>
    SZL,
    
    /// <remarks/>
    THB,
    
    /// <remarks/>
    TJS,
    
    /// <remarks/>
    TMT,
    
    /// <remarks/>
    TND,
    
    /// <remarks/>
    TOP,
    
    /// <remarks/>
    TRY,
    
    /// <remarks/>
    TTD,
    
    /// <remarks/>
    TWD,
    
    /// <remarks/>
    TZS,
    
    /// <remarks/>
    UAH,
    
    /// <remarks/>
    UGX,
    
    /// <remarks/>
    USD,
    
    /// <remarks/>
    USN,
    
    /// <remarks/>
    USS,
    
    /// <remarks/>
    UYI,
    
    /// <remarks/>
    UYU,
    
    /// <remarks/>
    UZS,
    
    /// <remarks/>
    VEF,
    
    /// <remarks/>
    VND,
    
    /// <remarks/>
    VUV,
    
    /// <remarks/>
    WST,
    
    /// <remarks/>
    XAF,
    
    /// <remarks/>
    XAG,
    
    /// <remarks/>
    XAU,
    
    /// <remarks/>
    XBA,
    
    /// <remarks/>
    XBB,
    
    /// <remarks/>
    XBC,
    
    /// <remarks/>
    XBD,
    
    /// <remarks/>
    XCD,
    
    /// <remarks/>
    XDR,
    
    /// <remarks/>
    XFU,
    
    /// <remarks/>
    XOF,
    
    /// <remarks/>
    XPD,
    
    /// <remarks/>
    XPF,
    
    /// <remarks/>
    XPT,
    
    /// <remarks/>
    XSU,
    
    /// <remarks/>
    XUA,
    
    /// <remarks/>
    XXX,
    
    /// <remarks/>
    YER,
    
    /// <remarks/>
    ZAR,
    
    /// <remarks/>
    ZMW,
    
    /// <remarks/>
    ZWL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class CARRef_Type {
    
    private string poolReportReportingFIGIINField;
    
    private string poolReportMessageRefIdField;
    
    private string poolReportDocRefIdField;
    
    /// <remarks/>
    public string PoolReportReportingFIGIIN {
        get {
            return this.poolReportReportingFIGIINField;
        }
        set {
            this.poolReportReportingFIGIINField = value;
        }
    }
    
    /// <remarks/>
    public string PoolReportMessageRefId {
        get {
            return this.poolReportMessageRefIdField;
        }
        set {
            this.poolReportMessageRefIdField = value;
        }
    }
    
    /// <remarks/>
    public string PoolReportDocRefId {
        get {
            return this.poolReportDocRefIdField;
        }
        set {
            this.poolReportDocRefIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class Payment_Type {
    
    private FatcaPaymentType_EnumType typeField;
    
    private string paymentTypeDescField;
    
    private MonAmnt_Type paymentAmntField;
    
    /// <remarks/>
    public FatcaPaymentType_EnumType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentTypeDesc {
        get {
            return this.paymentTypeDescField;
        }
        set {
            this.paymentTypeDescField = value;
        }
    }
    
    /// <remarks/>
    public MonAmnt_Type PaymentAmnt {
        get {
            return this.paymentAmntField;
        }
        set {
            this.paymentAmntField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public enum FatcaPaymentType_EnumType {
    
    /// <remarks/>
    FATCA501,
    
    /// <remarks/>
    FATCA502,
    
    /// <remarks/>
    FATCA503,
    
    /// <remarks/>
    FATCA504,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class SubstantialOwner_Type {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Individual", typeof(PersonParty_Type))]
    [System.Xml.Serialization.XmlElementAttribute("Organisation", typeof(OrganisationParty_Type))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class PersonParty_Type {
    
    private CountryCode_Type[] resCountryCodeField;
    
    private TIN_Type[] tINField;
    
    private NamePerson_Type[] nameField;
    
    private Address_Type[] addressField;
    
    private CountryCode_Type[] nationalityField;
    
    private PersonParty_TypeBirthInfo birthInfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResCountryCode")]
    public CountryCode_Type[] ResCountryCode {
        get {
            return this.resCountryCodeField;
        }
        set {
            this.resCountryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TIN")]
    public TIN_Type[] TIN {
        get {
            return this.tINField;
        }
        set {
            this.tINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Name")]
    public NamePerson_Type[] Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Address")]
    public Address_Type[] Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Nationality")]
    public CountryCode_Type[] Nationality {
        get {
            return this.nationalityField;
        }
        set {
            this.nationalityField = value;
        }
    }
    
    /// <remarks/>
    public PersonParty_TypeBirthInfo BirthInfo {
        get {
            return this.birthInfoField;
        }
        set {
            this.birthInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class TIN_Type {
    
    private CountryCode_Type issuedByField;
    
    private bool issuedByFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CountryCode_Type issuedBy {
        get {
            return this.issuedByField;
        }
        set {
            this.issuedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool issuedBySpecified {
        get {
            return this.issuedByFieldSpecified;
        }
        set {
            this.issuedByFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class NamePerson_Type {
    
    private string precedingTitleField;
    
    private string[] titleField;
    
    private NamePerson_TypeFirstName firstNameField;
    
    private NamePerson_TypeMiddleName[] middleNameField;
    
    private NamePerson_TypeNamePrefix namePrefixField;
    
    private NamePerson_TypeLastName lastNameField;
    
    private string[] generationIdentifierField;
    
    private string[] suffixField;
    
    private string generalSuffixField;
    
    private OECDNameType_EnumType nameTypeField;
    
    private bool nameTypeFieldSpecified;
    
    /// <remarks/>
    public string PrecedingTitle {
        get {
            return this.precedingTitleField;
        }
        set {
            this.precedingTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Title")]
    public string[] Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public NamePerson_TypeFirstName FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MiddleName")]
    public NamePerson_TypeMiddleName[] MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    public NamePerson_TypeNamePrefix NamePrefix {
        get {
            return this.namePrefixField;
        }
        set {
            this.namePrefixField = value;
        }
    }
    
    /// <remarks/>
    public NamePerson_TypeLastName LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GenerationIdentifier")]
    public string[] GenerationIdentifier {
        get {
            return this.generationIdentifierField;
        }
        set {
            this.generationIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Suffix")]
    public string[] Suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    public string GeneralSuffix {
        get {
            return this.generalSuffixField;
        }
        set {
            this.generalSuffixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public OECDNameType_EnumType nameType {
        get {
            return this.nameTypeField;
        }
        set {
            this.nameTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nameTypeSpecified {
        get {
            return this.nameTypeFieldSpecified;
        }
        set {
            this.nameTypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class NamePerson_TypeFirstName {
    
    private string xnlNameTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xnlNameType {
        get {
            return this.xnlNameTypeField;
        }
        set {
            this.xnlNameTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class NamePerson_TypeMiddleName {
    
    private string xnlNameTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xnlNameType {
        get {
            return this.xnlNameTypeField;
        }
        set {
            this.xnlNameTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class NamePerson_TypeNamePrefix {
    
    private string xnlNameTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xnlNameType {
        get {
            return this.xnlNameTypeField;
        }
        set {
            this.xnlNameTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class NamePerson_TypeLastName {
    
    private string xnlNameTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xnlNameType {
        get {
            return this.xnlNameTypeField;
        }
        set {
            this.xnlNameTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stf:v4")]
public enum OECDNameType_EnumType {
    
    /// <remarks/>
    OECD201,
    
    /// <remarks/>
    OECD202,
    
    /// <remarks/>
    OECD203,
    
    /// <remarks/>
    OECD204,
    
    /// <remarks/>
    OECD205,
    
    /// <remarks/>
    OECD206,
    
    /// <remarks/>
    OECD207,
    
    /// <remarks/>
    OECD208,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class Address_Type {
    
    private CountryCode_Type countryCodeField;
    
    private object[] itemsField;
    
    private OECDLegalAddressType_EnumType legalAddressTypeField;
    
    private bool legalAddressTypeFieldSpecified;
    
    /// <remarks/>
    public CountryCode_Type CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddressFix", typeof(AddressFix_Type))]
    [System.Xml.Serialization.XmlElementAttribute("AddressFree", typeof(string))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public OECDLegalAddressType_EnumType legalAddressType {
        get {
            return this.legalAddressTypeField;
        }
        set {
            this.legalAddressTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool legalAddressTypeSpecified {
        get {
            return this.legalAddressTypeFieldSpecified;
        }
        set {
            this.legalAddressTypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class AddressFix_Type {
    
    private string streetField;
    
    private string buildingIdentifierField;
    
    private string suiteIdentifierField;
    
    private string floorIdentifierField;
    
    private string districtNameField;
    
    private string pOBField;
    
    private string postCodeField;
    
    private string cityField;
    
    private string countrySubentityField;
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string BuildingIdentifier {
        get {
            return this.buildingIdentifierField;
        }
        set {
            this.buildingIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public string SuiteIdentifier {
        get {
            return this.suiteIdentifierField;
        }
        set {
            this.suiteIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public string FloorIdentifier {
        get {
            return this.floorIdentifierField;
        }
        set {
            this.floorIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public string DistrictName {
        get {
            return this.districtNameField;
        }
        set {
            this.districtNameField = value;
        }
    }
    
    /// <remarks/>
    public string POB {
        get {
            return this.pOBField;
        }
        set {
            this.pOBField = value;
        }
    }
    
    /// <remarks/>
    public string PostCode {
        get {
            return this.postCodeField;
        }
        set {
            this.postCodeField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string CountrySubentity {
        get {
            return this.countrySubentityField;
        }
        set {
            this.countrySubentityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stf:v4")]
public enum OECDLegalAddressType_EnumType {
    
    /// <remarks/>
    OECD301,
    
    /// <remarks/>
    OECD302,
    
    /// <remarks/>
    OECD303,
    
    /// <remarks/>
    OECD304,
    
    /// <remarks/>
    OECD305,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class PersonParty_TypeBirthInfo {
    
    private System.DateTime birthDateField;
    
    private bool birthDateFieldSpecified;
    
    private string cityField;
    
    private string citySubentityField;
    
    private PersonParty_TypeBirthInfoCountryInfo countryInfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BirthDateSpecified {
        get {
            return this.birthDateFieldSpecified;
        }
        set {
            this.birthDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string CitySubentity {
        get {
            return this.citySubentityField;
        }
        set {
            this.citySubentityField = value;
        }
    }
    
    /// <remarks/>
    public PersonParty_TypeBirthInfoCountryInfo CountryInfo {
        get {
            return this.countryInfoField;
        }
        set {
            this.countryInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class PersonParty_TypeBirthInfoCountryInfo {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CountryCode", typeof(CountryCode_Type))]
    [System.Xml.Serialization.XmlElementAttribute("FormerCountryName", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CorrectableReportOrganisation_Type))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class OrganisationParty_Type {
    
    private CountryCode_Type[] resCountryCodeField;
    
    private TIN_Type[] tINField;
    
    private NameOrganisation_Type[] nameField;
    
    private Address_Type[] addressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResCountryCode")]
    public CountryCode_Type[] ResCountryCode {
        get {
            return this.resCountryCodeField;
        }
        set {
            this.resCountryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TIN")]
    public TIN_Type[] TIN {
        get {
            return this.tINField;
        }
        set {
            this.tINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Name")]
    public NameOrganisation_Type[] Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Address")]
    public Address_Type[] Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stffatcatypes:v2")]
public partial class NameOrganisation_Type {
    
    private OECDNameType_EnumType nameTypeField;
    
    private bool nameTypeFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public OECDNameType_EnumType nameType {
        get {
            return this.nameTypeField;
        }
        set {
            this.nameTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nameTypeSpecified {
        get {
            return this.nameTypeFieldSpecified;
        }
        set {
            this.nameTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class CorrectableReportOrganisation_Type : OrganisationParty_Type {
    
    private FatcaFilerCategory_EnumType filerCategoryField;
    
    private bool filerCategoryFieldSpecified;
    
    private DocSpec_Type docSpecField;
    
    /// <remarks/>
    public FatcaFilerCategory_EnumType FilerCategory {
        get {
            return this.filerCategoryField;
        }
        set {
            this.filerCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FilerCategorySpecified {
        get {
            return this.filerCategoryFieldSpecified;
        }
        set {
            this.filerCategoryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public DocSpec_Type DocSpec {
        get {
            return this.docSpecField;
        }
        set {
            this.docSpecField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public enum FatcaFilerCategory_EnumType {
    
    /// <remarks/>
    FATCA601,
    
    /// <remarks/>
    FATCA602,
    
    /// <remarks/>
    FATCA603,
    
    /// <remarks/>
    FATCA604,
    
    /// <remarks/>
    FATCA605,
    
    /// <remarks/>
    FATCA606,
    
    /// <remarks/>
    FATCA607,
    
    /// <remarks/>
    FATCA608,
    
    /// <remarks/>
    FATCA609,
    
    /// <remarks/>
    FATCA610,
    
    /// <remarks/>
    FATCA611,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class AccountHolder_Type {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AcctHolderType", typeof(FatcaAcctHolderType_EnumType))]
    [System.Xml.Serialization.XmlElementAttribute("Individual", typeof(PersonParty_Type))]
    [System.Xml.Serialization.XmlElementAttribute("Organisation", typeof(OrganisationParty_Type))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public enum FatcaAcctHolderType_EnumType {
    
    /// <remarks/>
    FATCA101,
    
    /// <remarks/>
    FATCA102,
    
    /// <remarks/>
    FATCA103,
    
    /// <remarks/>
    FATCA104,
    
    /// <remarks/>
    FATCA105,
    
    /// <remarks/>
    FATCA106,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class FIAccountNumber_Type {
    
    private AcctNumberType_EnumType acctNumberTypeField;
    
    private bool acctNumberTypeFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AcctNumberType_EnumType AcctNumberType {
        get {
            return this.acctNumberTypeField;
        }
        set {
            this.acctNumberTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AcctNumberTypeSpecified {
        get {
            return this.acctNumberTypeFieldSpecified;
        }
        set {
            this.acctNumberTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:stf:v4")]
public enum AcctNumberType_EnumType {
    
    /// <remarks/>
    OECD601,
    
    /// <remarks/>
    OECD602,
    
    /// <remarks/>
    OECD603,
    
    /// <remarks/>
    OECD604,
    
    /// <remarks/>
    OECD605,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class CorrectableAccountReport_Type {
    
    private DocSpec_Type docSpecField;
    
    private FIAccountNumber_Type accountNumberField;
    
    private bool accountClosedField;
    
    private bool accountClosedFieldSpecified;
    
    private AccountHolder_Type accountHolderField;
    
    private SubstantialOwner_Type[] substantialOwnerField;
    
    private MonAmnt_Type accountBalanceField;
    
    private Payment_Type[] paymentField;
    
    private CARRef_Type cARRefField;
    
    private AdditionalData_TypeAdditionalItem[] additionalDataField;
    
    /// <remarks/>
    public DocSpec_Type DocSpec {
        get {
            return this.docSpecField;
        }
        set {
            this.docSpecField = value;
        }
    }
    
    /// <remarks/>
    public FIAccountNumber_Type AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public bool AccountClosed {
        get {
            return this.accountClosedField;
        }
        set {
            this.accountClosedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccountClosedSpecified {
        get {
            return this.accountClosedFieldSpecified;
        }
        set {
            this.accountClosedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public AccountHolder_Type AccountHolder {
        get {
            return this.accountHolderField;
        }
        set {
            this.accountHolderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubstantialOwner")]
    public SubstantialOwner_Type[] SubstantialOwner {
        get {
            return this.substantialOwnerField;
        }
        set {
            this.substantialOwnerField = value;
        }
    }
    
    /// <remarks/>
    public MonAmnt_Type AccountBalance {
        get {
            return this.accountBalanceField;
        }
        set {
            this.accountBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Payment")]
    public Payment_Type[] Payment {
        get {
            return this.paymentField;
        }
        set {
            this.paymentField = value;
        }
    }
    
    /// <remarks/>
    public CARRef_Type CARRef {
        get {
            return this.cARRefField;
        }
        set {
            this.cARRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AdditionalItem", IsNullable=false)]
    public AdditionalData_TypeAdditionalItem[] AdditionalData {
        get {
            return this.additionalDataField;
        }
        set {
            this.additionalDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:fatca:v2")]
public partial class AdditionalData_TypeAdditionalItem {
    
    private string itemNameField;
    
    private string itemContentField;
    
    /// <remarks/>
    public string ItemName {
        get {
            return this.itemNameField;
        }
        set {
            this.itemNameField = value;
        }
    }
    
    /// <remarks/>
    public string ItemContent {
        get {
            return this.itemContentField;
        }
        set {
            this.itemContentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class CorrectableNilReport_Type {
    
    private DocSpec_Type docSpecField;
    
    private string noAccountToReportField;
    
    public CorrectableNilReport_Type() {
        this.noAccountToReportField = "yes";
    }
    
    /// <remarks/>
    public DocSpec_Type DocSpec {
        get {
            return this.docSpecField;
        }
        set {
            this.docSpecField = value;
        }
    }
    
    /// <remarks/>
    public string NoAccountToReport {
        get {
            return this.noAccountToReportField;
        }
        set {
            this.noAccountToReportField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:fatca:v2")]
public partial class Fatca_Type {
    
    private CorrectableReportOrganisation_Type reportingFIField;
    
    private Fatca_TypeReportingGroup[] reportingGroupField;
    
    /// <remarks/>
    public CorrectableReportOrganisation_Type ReportingFI {
        get {
            return this.reportingFIField;
        }
        set {
            this.reportingFIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReportingGroup")]
    public Fatca_TypeReportingGroup[] ReportingGroup {
        get {
            return this.reportingGroupField;
        }
        set {
            this.reportingGroupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:fatca:v2")]
public partial class Fatca_TypeReportingGroup {
    
    private CorrectableReportOrganisation_Type sponsorField;
    
    private CorrectableReportOrganisation_Type intermediaryField;
    
    private object[] itemsField;
    
    /// <remarks/>
    public CorrectableReportOrganisation_Type Sponsor {
        get {
            return this.sponsorField;
        }
        set {
            this.sponsorField = value;
        }
    }
    
    /// <remarks/>
    public CorrectableReportOrganisation_Type Intermediary {
        get {
            return this.intermediaryField;
        }
        set {
            this.intermediaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AccountReport", typeof(CorrectableAccountReport_Type))]
    [System.Xml.Serialization.XmlElementAttribute("NilReport", typeof(CorrectableNilReport_Type))]
    [System.Xml.Serialization.XmlElementAttribute("PoolReport", typeof(CorrectablePoolReport_Type))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
